#! /bin/bash
#
# README.md: 
# https://github.com/rayelnigma/bash-boilerplate/blob/master/README.md
# 
# A boilerplate/template for a bash script.  The intention 
# of this script is so that I can copy/paste it into a new 
# location, rename the script, and then start writing code.  
# Having functionality to all of my favorite features that 
# I 'grew up with' ;-)
#

# remember to replace the 'rename-me' with your new script name
_THIS_SCRIPT="rename-me"
_LOG_DIR="/var/log/${_THIS_SCRIPT}"
LOG="${_LOG_DIR}/${_THIS_SCRIPT}.log"
debug="true"

# make sure we can do our logging to the file system...
mkdir -p ${_LOG_DIR}
if [ $? == "1" ] 
  then
    echo "error creating ${_LOG_DIR}, exiting"
	  exit 1
fi

function log() {
	DATE="date +%Y%m%d%H%M%S"
	echo "$(${DATE}):${1}: ${2}"
	echo "$(${DATE}):${1}: ${2}" >> ${LOG}
}

function debug() {
	if [ ${debug} == "true" ]
	  then
		  log "D" "${1}"
	fi
}

function info() {
  log "I" "${1}"
}

function warn() {
	log "W" "${1}"
}

function error() {
	log "E" "${1}"
}

function fatal() {
	log "F" "${1}"
	die "${1}"
}

function logVariable() {
	debug "${1}=${!1}"
}

function begin() {
	debug "--> begin... ${1} --------->"
}

function end() {
	debug "<----------- ${1} ...end <--"
}

function initialize() {
	begin "INITIALIZE"
	logVariable _THIS_SCRIPT
	logVariable LOG
	logVariable debug
	# more variables go here:

	end "INITIALIZE"
}

#debug="false"
initialize



